/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountRow: typeof import('./src/components/AccountRow.vue')['default']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    IMdiEyeOffOutline: typeof import('~icons/mdi/eye-off-outline')['default']
    IMdiEyeOutline: typeof import('~icons/mdi/eye-outline')['default']
    IMdiHelpCircleOutline: typeof import('~icons/mdi/help-circle-outline')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiTrashCanOutline: typeof import('~icons/mdi/trash-can-outline')['default']
  }
}
